spring.application.name=PFT

## Database Properties
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/pft?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = validate

#JWT
app.jwt.secret=${SECRET_KEY}
app.jwt.expiration-seconds=3600
app.jwt.issuer=pft

#Mail
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
